// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sruazvyuxgmpeduofpmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydWF6dnl1eGdtcGVkdW9mcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTIxMzMsImV4cCI6MjA2NDQ4ODEzM30.7CA4O2TDd4nJqIYuOsgU3OflODu72QbtE1GkpvFtYvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);